In [2]:
import pandas as pd
import numpy as np
import openpyxl
from pathlib import Path

In [3]:
#Extraer el dataset original verificación de las primeras 5 filas
PROJECT_ROOT = Path.cwd().parent
file_path = PROJECT_ROOT / "data" / "processed" / "ventasTransformed.csv"
#asegurar el tipo de dato float para columnas decimales
column_type={"PrecioUnitarioProducto1": float, "SubtotalProducto1": float, "PrecioUnitarioProducto2": float,
    "SubtotalProducto2": float,"PrecioUnitarioProducto3": float, "SubtotalProducto3": float, "TotalVenta": float}
dataset = pd.read_csv(file_path, sep= "\t", dtype= column_type, encoding="utf-8")
#Leer la hora con formato  AM/PM
dataset["HoraVenta"]=pd.to_datetime(dataset["HoraVenta"], format="%I:%M:%S %p").dt.time
dataset.head()

,VentaID,HoraVenta,SucursalNombre,VendedorNombre,ClienteNombre,GeneroCliente,EdadCliente,EmailCliente,TelefonoCliente,DireccionCliente,...,CantidadProducto3,PrecioUnitarioProducto3,SubtotalProducto3,DescuentoVenta,TotalVenta,CiudadSucursal,MarcaProducto1,MarcaProducto2,MarcaProducto3,FechaVenta
0,240,23:28:42,Techcore Medellin#2,Claudia Sastre Quintero,Panfilo Salazar,M,25,panfilo11@yahoo.com,+34920728807,cra 55 #46-70,...,0,0.0,0.0,0.0,5200000.0,Medellin,HP,No registrado,No registrado,"Tuesday, December 7, 2021"
1,637,23:02:30,Techcore Medellin#1,Ana Sofia Llopis Blazquez,Crescencia Gutierrez Gimenez,F,18,crescencia98@hotmail.com,+34883141900,cra 60 #66-27,...,0,0.0,0.0,0.0,5200000.0,Medellin,HP,No registrado,No registrado,"Saturday, July 15, 2017"
2,1096,07:53:12,Techcore Medellin#1,Eusebia Jara Macias,Candido Pastor Plana,M,21,candido49@gmail.com,+34943846175,cll 33 #11-22,...,0,0.0,0.0,0.0,5200000.0,Medellin,HP,No registrado,No registrado,"Monday, March 27, 2023"
3,1249,16:51:13,Techcore Medellin#2,Juan Jose Porcel Riera,Goyo Garriga Jove,M,25,goyo24@gmail.com,+34921230732,cll 21 #97-27,...,0,0.0,0.0,0.0,5200000.0,Medellin,HP,No registrado,No registrado,"Saturday, December 16, 2023"
4,1346,10:06:21,Techcore Medellin#1,Dominga del Alcantara,Florentino Ros Rovira,M,42,florentino54@hotmail.com,+34900231150,cll 14 #76-41,...,0,0.0,0.0,0.0,5200000.0,Medellin,HP,No registrado,No registrado,"Sunday, September 27, 2015"

In [4]:
#verificación 5 últimas filas
dataset.tail()

,VentaID,HoraVenta,SucursalNombre,VendedorNombre,ClienteNombre,GeneroCliente,EdadCliente,EmailCliente,TelefonoCliente,DireccionCliente,...,CantidadProducto3,PrecioUnitarioProducto3,SubtotalProducto3,DescuentoVenta,TotalVenta,CiudadSucursal,MarcaProducto1,MarcaProducto2,MarcaProducto3,FechaVenta
29995,29154,02:05:29,Techcore Bogota#2,Armida Azorin Plaza,Celestina Ferrandiz Padilla,F,19,celestina66@yahoo.com,+34980541976,cll 9 #59-25,...,1,2800000.0,2800000.0,0.0,20000000.0,Bogota,HP,HP,Lenovo,"Monday, July 12, 2021"
29996,29611,12:55:00,Techcore Medellin#2,Juan Jose Porcel Riera,Gervasio Millan Barros,M,50,gervasio86@yahoo.com,+34826887292,cll 30 #93-78,...,1,6800000.0,6800000.0,0.0,22000000.0,Medellin,Samsung,Asus,Lenovo,"Wednesday, October 13, 2021"
29997,29659,02:57:55,Techcore Bogota#2,Herminia Melendez Huguet,Evaristo Canton Sedano,M,26,evaristo65@yahoo.com,+34983239566,cll 42 #55-72,...,1,4400000.0,4400000.0,0.0,25200000.0,Bogota,Asus,Lenovo,Lenovo,"Saturday, September 15, 2018"
29998,29714,15:48:35,Techcore Medellin#1,Dominga del Alcantara,Ivan Duilio Mulet Bonilla,M,24,No registrado,+34976371059,cll 64 #17-27,...,1,4400000.0,4400000.0,0.0,22000000.0,Medellin,Asus,Asus,Lenovo,"Friday, April 14, 2023"
29999,29921,03:59:24,Techcore Bogota#2,Armida Azorin Plaza,Albert Antonio Prado Sanjuan,M,49,albert22@hotmail.com,+34914997232,cra 97 #89-99,...,1,6800000.0,6800000.0,0.0,27600000.0,Bogota,Dell,Apple,Lenovo,"Sunday, June 22, 2025"

In [5]:
#Verificación general de toda la data
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   VentaID                  30000 non-null  int64
 1   HoraVenta                30000 non-null  object
 2   SucursalNombre           30000 non-null  str
 3   VendedorNombre           30000 non-null  str
 4   ClienteNombre            30000 non-null  str
 5   GeneroCliente            30000 non-null  str
 6   EdadCliente              30000 non-null  int64
 7   EmailCliente             30000 non-null  str
 8   TelefonoCliente          30000 non-null  str
 9   DireccionCliente         30000 non-null  str
 10  MetodoPago               30000 non-null  str
 11  NombreProducto1          30000 non-null  str
 12  CantidadProducto1        30000 non-null  int64
 13  PrecioUnitarioProducto1  30000 non-null  float64
 14  SubtotalProducto1        30000 non-null  float64
 15  NombreProducto2          30000 non-null  str
 16  CantidadProducto2        30000 non-null  int64
 17  PrecioUnitarioProducto2  30000 non-null  float64
 18  SubtotalProducto2        30000 non-null  float64
 19  NombreProducto3          30000 non-null  str
 20  CantidadProducto3        30000 non-null  int64
 21  PrecioUnitarioProducto3  30000 non-null  float64
 22  SubtotalProducto3        30000 non-null  float64
 23  DescuentoVenta           30000 non-null  float64
 24  TotalVenta               30000 non-null  float64
 25  CiudadSucursal           30000 non-null  str
 26  MarcaProducto1           30000 non-null  str
 27  MarcaProducto2           30000 non-null  str
 28  MarcaProducto3           30000 non-null  str
 29  FechaVenta               30000 non-null  str
dtypes: float64(8), int64(5), object(1), str(16)
memory usage: 13.0+ MB

Creación de tablas: Ciudad, Vendedores, Clientes, Productos, Fechas, Sucursales, Facturas y Detalles Facturas.

In [6]:
#Tabla ciudad

cities= sorted(dataset["CiudadSucursal"].unique())
cityID = range(1, len(cities)+1)
dt_City= pd.DataFrame({"CiudadID": cityID ,"NombreCiudad": cities})
dt_City.head()

   CiudadID NombreCiudad
0         1       Bogota
1         2         Cali
2         3     Medellin
3         4      Pereira

In [7]:
#Tabla vendedores
salesperson = sorted(dataset["VendedorNombre"].unique())
SPersonID = range(1, len(salesperson)+1)
dt_SalesPerson = pd.DataFrame({"VendedorID": SPersonID, "NombreVendedor": salesperson})
dt_SalesPerson.head()

   VendedorID                   NombreVendedor
0           1  Almudena Adelaida Lledo Garrido
1           2           Amilcar Ortega Alberto
2           3        Ana Sofia Llopis Blazquez
3           4          Anacleto Morera Segovia
4           5              Armida Azorin Plaza

In [8]:
#Tabla Clientes
dt_Client = dataset[["ClienteNombre","GeneroCliente", "EdadCliente", "TelefonoCliente", "EmailCliente", "DireccionCliente"]]
dt_Client = dt_Client.drop_duplicates(subset="ClienteNombre").reset_index(drop=True)
dt_Client["ClienteID"] = range(1, len(dt_Client["ClienteNombre"])+1)
columnOrder = ["ClienteID","ClienteNombre","GeneroCliente", "EdadCliente", "TelefonoCliente", "EmailCliente", "DireccionCliente"]
dt_Client = dt_Client[columnOrder]


dt_Client.head()

,ClienteID,ClienteNombre,GeneroCliente,EdadCliente,TelefonoCliente,EmailCliente,DireccionCliente
0,1,Panfilo Salazar,M,25,+34920728807,panfilo11@yahoo.com,cra 55 #46-70
1,2,Crescencia Gutierrez Gimenez,F,18,+34883141900,crescencia98@hotmail.com,cra 60 #66-27
2,3,Candido Pastor Plana,M,21,+34943846175,candido49@gmail.com,cll 33 #11-22
3,4,Goyo Garriga Jove,M,25,+34921230732,goyo24@gmail.com,cll 21 #97-27
4,5,Florentino Ros Rovira,M,42,+34900231150,florentino54@hotmail.com,cll 14 #76-41

In [9]:
#Tabla Productos
productslist = pd.concat([dataset["NombreProducto1"], dataset["NombreProducto2"], dataset["NombreProducto3"]], ignore_index=True)
brandlist = pd.concat([dataset["MarcaProducto1"], dataset["MarcaProducto2"], dataset["MarcaProducto3"]], ignore_index=True)
pricelist = pd.concat([dataset["PrecioUnitarioProducto1"], dataset["PrecioUnitarioProducto2"], dataset["PrecioUnitarioProducto3"]], ignore_index=True)

dt_temporary = pd.DataFrame({"NombreProducto": productslist, "MarcaProducto": brandlist, "PrecioUnitario": pricelist})
dt_product = dt_temporary.drop_duplicates(subset="NombreProducto").reset_index(drop=True)
dt_product["ProductoID"] = range(1, len(dt_product["NombreProducto"])+1)
columnOrderP = ["ProductoID", "NombreProducto", "MarcaProducto", "PrecioUnitario"]
dt_product = dt_product[columnOrderP]
dt_product.head()

   ProductoID   NombreProducto MarcaProducto  PrecioUnitario
0           1  HP Spectre x360            HP       5200000.0
1           2       HP Omen 16            HP       6000000.0
2           3   HP Pavilion 15            HP       3500000.0
3           4       HP Envy 13            HP       4000000.0
4           5   Lenovo Yoga 7i        Lenovo       4400000.0

In [10]:
#Tabla fecha
dataset["FechaVenta"] = pd.to_datetime(dataset["FechaVenta"])
startYear= dataset["FechaVenta"].min().year
endYear = dataset["FechaVenta"].max().year
print(f"Primer año de venta:{startYear}. Último año de venta registrado: {endYear}")

completeRange = pd.date_range(start=f"{startYear}-01-01", end=f"{endYear}-12-31")
dt_temporary_date = pd.DataFrame({"FechaBase": completeRange})

monthName = {1:"Enero", 2:"Febrero", 3:"Marzo", 4:"Abril", 5:"Mayo", 6:"Junio", 7:"Julio",
          8:"Agosto", 9:"Septiembre", 10:"Octubre", 11:"Noviembre", 12:"Diciembre"}

dayName = {0:"Lunes", 1:"Martes", 2:"Miercoles", 3:"Jueves", 4:"Viernes", 5:"Sabado", 6: "Domingo"}

dt_date = pd.DataFrame({"FechaID": dt_temporary_date["FechaBase"].dt.strftime('%Y%m%d').astype(int),
                        "FechaVenta": dt_temporary_date["FechaBase"].dt.strftime('%Y/%m/%d') ,
                        "AñoVenta": dt_temporary_date["FechaBase"].dt.year ,
                        "MesVenta": dt_temporary_date["FechaBase"].dt.month ,
                        "MesNombre": dt_temporary_date["FechaBase"].dt.month.map(monthName) ,
                        "DiaVenta": dt_temporary_date["FechaBase"].dt.day,
                        "DiaNombre": dt_temporary_date["FechaBase"].dt.dayofweek.map(dayName),
                        "Trimeste": 'Q'+dt_temporary_date["FechaBase"].dt.quarter.astype(str),
                        "EsFinDeSemana": dt_temporary_date["FechaBase"].dt.dayofweek.isin([5,6]).map({True: "Si",False: "No"})})

dt_date.head()

Primer año de venta:2014. Último año de venta registrado: 2025

,FechaID,FechaVenta,AñoVenta,MesVenta,MesNombre,DiaVenta,DiaNombre,Trimeste,EsFinDeSemana
0,20140101,2014/01/01,2014,1,Enero,1,Miercoles,Q1,No
1,20140102,2014/01/02,2014,1,Enero,2,Jueves,Q1,No
2,20140103,2014/01/03,2014,1,Enero,3,Viernes,Q1,No
3,20140104,2014/01/04,2014,1,Enero,4,Sabado,Q1,Si
4,20140105,2014/01/05,2014,1,Enero,5,Domingo,Q1,Si

In [11]:
dt_date.tail()

,FechaID,FechaVenta,AñoVenta,MesVenta,MesNombre,DiaVenta,DiaNombre,Trimeste,EsFinDeSemana
4378,20251227,2025/12/27,2025,12,Diciembre,27,Sabado,Q4,Si
4379,20251228,2025/12/28,2025,12,Diciembre,28,Domingo,Q4,Si
4380,20251229,2025/12/29,2025,12,Diciembre,29,Lunes,Q4,No
4381,20251230,2025/12/30,2025,12,Diciembre,30,Martes,Q4,No
4382,20251231,2025/12/31,2025,12,Diciembre,31,Miercoles,Q4,No

In [12]:
#Tabla Sucursal
dt_branch = dataset[["SucursalNombre", "CiudadSucursal"]].drop_duplicates(subset="SucursalNombre").reset_index(drop=True)
dt_branch["SucursalID"] = range(1, len(dt_branch)+1)
#Búsqueda del ID en la tabla de ciudad, funciona igual que un join
dt_branch = dt_branch.merge(right= dt_City, left_on="CiudadSucursal", right_on="NombreCiudad", how= "left")
columnOrderS = ["SucursalID", "CiudadID", "SucursalNombre"]
dt_branch = dt_branch[columnOrderS]

dt_branch.head()

   SucursalID  CiudadID       SucursalNombre
0           1         3  Techcore Medellin#2
1           2         3  Techcore Medellin#1
2           3         1    Techcore Bogota#1
3           4         1    Techcore Bogota#2
4           5         4     Techcore Pereira

In [13]:
#Tabla Facturas
dt_invoice = dataset[["TotalVenta","HoraVenta","MetodoPago","DescuentoVenta","FechaVenta", "SucursalNombre","VendedorNombre","ClienteNombre"]]
dt_invoice["FacturaID"] = range(1, len(dt_invoice)+1)
#Llamar a todas las claves
dt_invoice = dt_invoice.merge(right=dt_Client[["ClienteID","ClienteNombre"]],left_on="ClienteNombre",right_on="ClienteNombre", how="left")
dt_invoice = dt_invoice.merge(right=dt_SalesPerson,left_on="VendedorNombre",right_on="NombreVendedor", how="left")
dt_invoice = dt_invoice.merge(right=dt_branch[["SucursalID","SucursalNombre"]], left_on="SucursalNombre", right_on="SucursalNombre", how="left")
dt_invoice["FechaVenta"] = dt_invoice["FechaVenta"].dt.strftime('%Y/%m/%d')
dt_invoice = dt_invoice.merge(right=dt_date[["FechaVenta","FechaID"]], left_on="FechaVenta",right_on="FechaVenta",how="left")
dt_invoice = dt_invoice.rename(columns={"DescuentoVenta": "Descuento"})
columnOrderI = ["FacturaID","ClienteID","VendedorID","SucursalID","FechaID", "HoraVenta", "MetodoPago", "Descuento", "TotalVenta"]
dt_invoice = dt_invoice[columnOrderI]
dt_invoice.head()

,FacturaID,ClienteID,VendedorID,SucursalID,FechaID,HoraVenta,MetodoPago,Descuento,TotalVenta
0,1,1,9,1,20211207,23:28:42,Tarjeta Credito,0.0,5200000.0
1,2,2,3,2,20170715,23:02:30,Tarjeta Credito,0.0,5200000.0
2,3,3,14,2,20230327,07:53:12,Tarjeta Credito,0.0,5200000.0
3,4,4,22,1,20231216,16:51:13,Tarjeta Credito,0.0,5200000.0
4,5,5,11,2,20150927,10:06:21,Tarjeta Credito,0.0,5200000.0

In [14]:
dt_invoice.tail()

,FacturaID,ClienteID,VendedorID,SucursalID,FechaID,HoraVenta,MetodoPago,Descuento,TotalVenta
29995,29996,7412,5,4,20210712,02:05:29,Tarjeta Credito,0.0,20000000.0
29996,29997,17447,22,1,20211013,12:55:00,Tarjeta Credito,0.0,22000000.0
29997,29998,17448,18,4,20180915,02:57:55,Tarjeta Credito,0.0,25200000.0
29998,29999,2997,11,2,20230414,15:48:35,Tarjeta Credito,0.0,22000000.0
29999,30000,17449,5,4,20250622,03:59:24,Tarjeta Credito,0.0,27600000.0

In [15]:
#Tabla Detalle Factura
dataset["FilaPuente"] = range(1, len(dataset)+1)
dt_detailInvoice = pd.concat([dataset[["FilaPuente","NombreProducto1","CantidadProducto1","PrecioUnitarioProducto1","SubtotalProducto1"]]
                              .set_axis(["FilaPuente","NombreProducto","Cantidad","PrecioUnitario", "subtotal"], axis=1)
                              ,dataset[["FilaPuente","NombreProducto2","CantidadProducto2","PrecioUnitarioProducto2","SubtotalProducto2"]]
                              .set_axis(["FilaPuente","NombreProducto","Cantidad","PrecioUnitario", "subtotal"], axis=1)
                              , dataset[["FilaPuente","NombreProducto3","CantidadProducto3","PrecioUnitarioProducto3","SubtotalProducto3"]]
                              .set_axis(["FilaPuente","NombreProducto","Cantidad","PrecioUnitario", "subtotal"], axis=1)]
                              , ignore_index=True)

dt_detailInvoice = dt_detailInvoice[dt_detailInvoice["NombreProducto"]!="No registrado"].reset_index(drop = True)

dt_detailInvoice ["DetalleID"] = range(1, len(dt_detailInvoice)+1)
dt_detailInvoice = dt_detailInvoice.merge(right=dt_product[["ProductoID","NombreProducto"]], left_on="NombreProducto"
                                          , right_on="NombreProducto", how="left")
dt_detailInvoice = dt_detailInvoice.merge(right=dt_invoice["FacturaID"],left_on="FilaPuente", right_on="FacturaID", how="left")
columnOrderDI = ["DetalleID","FacturaID","ProductoID","Cantidad","PrecioUnitario", "subtotal"]
dt_detailInvoice = dt_detailInvoice[columnOrderDI]
dt_detailInvoice.head()

   DetalleID  FacturaID  ProductoID  Cantidad  PrecioUnitario   subtotal
0          1          1           1         1       5200000.0  5200000.0
1          2          2           1         1       5200000.0  5200000.0
2          3          3           1         1       5200000.0  5200000.0
3          4          4           1         1       5200000.0  5200000.0
4          5          5           1         1       5200000.0  5200000.0

In [16]:
dt_detailInvoice.tail()

       DetalleID  FacturaID  ProductoID  Cantidad  PrecioUnitario   subtotal
60054      60055      29996           6         1       2800000.0  2800000.0
60055      60056      29997           8         1       6800000.0  6800000.0
60056      60057      29998           5         1       4400000.0  4400000.0
60057      60058      29999           5         1       4400000.0  4400000.0
60058      60059      30000           8         1       6800000.0  6800000.0

In [18]:
#Exportar a un archivo de excel
Final_File = PROJECT_ROOT / "data" / "processed" / "modeloVentas.xlsx"

# 2. Creamos el escritor de Excel de Pandas
with pd.ExcelWriter(Final_File, engine='openpyxl') as writer:
    # Guardamos las 6 Tablas  sin el índice de Python
    dt_City.to_excel(writer, sheet_name="Ciudad", index=False)
    dt_SalesPerson.to_excel(writer, sheet_name="Vendedores", index=False)
    dt_Client.to_excel(writer, sheet_name="Clientes", index=False)
    dt_product.to_excel(writer, sheet_name="Productos", index=False)
    dt_date.to_excel(writer, sheet_name="Fechas", index=False)
    dt_branch.to_excel(writer, sheet_name="Sucursales", index=False)
    
    # Guardamos las 2 Tablas de Hechos
    dt_invoice.to_excel(writer, sheet_name="Facturas", index=False)
    dt_detailInvoice.to_excel(writer, sheet_name="Detalles Facturas", index=False)

print(f"Se ha creado el archivo '{Final_File.name}' con las 8 tablas distribuidas en pestañas.")

Se ha creado el archivo 'modeloVentas.xlsx' con las 8 tablas distribuidas en pestañas.